version: "3.7"

services: 
  # the webserver itself
  webserver:
    restart: unless-stopped
    build:
      context: .
    volumes:
      - cargo:/home/rust/.cargo
      - target:/home/rust/src/target
    ports:
      - 4723:4723
    expose:
      - 4723

  # redis instance
  redis:
    image: "redis:5-alpine"
    ports:
      - "6379:6379"
    expose:
      - "6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 5s
    volumes:
      - "redis_data:/data"

volumes:
  cargo:
  redis_data:
  target: